### ISSUE TITLE
map merge fail ?

### ISSUE THREAD

**Issue by Sorrowa** [efc-robot/SMMR-Explore#5]
Thank you very much for sharing your team's outstanding work.

It seems that the map merge would not be triggered, according to the default configuration of this project (SMMR). 

How should I modify the code(in SMMR) to achieve map merging? (The "match_stamps_to_TF"  started smoothly.)

( I am trying to  establish tf associations between different robots (based on your team's Explore Bench code, thank you very much). But it didn't help to achieve the performance in the video(https://www.bilibili.com/video/BV1QT4y1F71u/).)

Sincerely hope to receive your guidance.

**Comment by Sorrowa** [comment]
i solve it.

**Comment by kjhxjm** [comment]
Hello,can you tell me how to solve it?Thank you very much.

**Comment by Sorrowa** [comment]
> Hello,can you tell me how to solve it?Thank you very much.

check every imports of python scripts. (my problem is due to torch and cuda)
